# Ruff configuration for linting and formatting
# Documentation: https://docs.astral.sh/ruff/

line-length = 100
target-version = "py313"

[lint]
# Enable carefully selected rule sets for personal project
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "UP",  # pyupgrade (modernize Python code)
]

# Ignore rules that are too strict for personal project
ignore = [
    "E501",  # Line too long (handled by formatter)
]

[lint.per-file-ignores]
# Tests can use assert
"tests/**/*.py" = ["S101"]

[format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Respect magic trailing comma
skip-magic-trailing-comma = false
