"""Constants used throughout the diary system."""

# Entry content thresholds
MIN_SUBSTANTIAL_CONTENT_CHARS = 50

# LLM Analysis limits
MAX_SEMANTIC_LINK_CANDIDATES = 20
MAX_SEMANTIC_LINKS = 5
MAX_TOPIC_TAGS = 5
ENTRY_PREVIEW_LENGTH = 400  # Increased for better topic diversity
TARGET_PREVIEW_LENGTH = 500

# Jaccard similarity threshold
JACCARD_SIMILARITY_THRESHOLD = 0.08

# Analysis parameters
DEFAULT_THEMES_COUNT = 10
MEMORY_TRACE_TOP_THEMES = 15
TOP_CONNECTED_ENTRIES = 5

# LLM parameters
LLM_TIMEOUT_SECONDS = 300.0  # 5 minutes
LLM_CONNECTION_CHECK_TIMEOUT = 5.0

# Prompt generation
DAILY_PROMPT_COUNT = 3
WEEKLY_PROMPT_COUNT = 5
PROMPT_CONTEXT_DAYS = 3
WEEKLY_CONTEXT_DAYS = 7
PROMPT_TEMPERATURE = 0.8
PROMPT_MAX_TOKENS = 300
WEEKLY_PROMPT_MAX_TOKENS = 500

# Semantic analysis
SEMANTIC_TEMPERATURE = 0.3
SEMANTIC_MAX_TOKENS = 200
TAG_TEMPERATURE = 0.5
TAG_MAX_TOKENS = 100

# Tag validation
MIN_TAG_LENGTH = 3
MAX_TAG_LENGTH = 15
MIN_THEME_OCCURRENCES = 2

# Context lookback
PAST_ENTRIES_LOOKBACK_DAYS = 90
